### ISSUE TITLE
As a user I want to select a round-trip ticket when I book the flight So I can book a trip with fewer efforts

### ISSUE THREAD

**Issue by ting-hu** [codemasterdev/Project-1#7]
Given a search website for the user input 
-- When I check the round-trip search checkbox
    Then I am presented with the flight tickets from one place to another and then return 
    back to the place that left 
-- When I uncheck the round-trip search checkbox
    Then I am presented with the search main page with no flight tickets results

**Comment by DaveToth77** [comment]
done
